### ISSUE TITLE
Client disconnecting on large payload with undefined property error

### ISSUE THREAD

**Issue by rafsawicki** [shanewholloway/js-u8-mqtt-packet#10]
When using u8-mqtt on the server I've ran into a bug, where receiving a large message (around 10MB when saved as JSON) results in an error and the connection being closed. The same message is processed correctly using MQTT.js, so it doesn't seem that the broker is at fault. Here's what error looks like when logged to the console using `log_conn` callback.

```
log_conn on_disconnect false TypeError: Cannot read properties of undefined (reading 'type')
    at mqtt_reader.props (/home/rafsawicki/dev/mqtt_test/node_modules/u8-mqtt/cjs/index.cjs:167:27)
    at ns.<computed> (/home/rafsawicki/dev/mqtt_test/node_modules/u8-mqtt/cjs/index.cjs:397:23)
    at Object.decode_pkt (/home/rafsawicki/dev/mqtt_test/node_modules/u8-mqtt/cjs/index.cjs:1050:25)
    at Object.decode (/home/rafsawicki/dev/mqtt_test/node_modules/u8-mqtt/cjs/index.cjs:1008:21)
    at on_mqtt_chunk (/home/rafsawicki/dev/mqtt_test/node_modules/u8-mqtt/cjs/index.cjs:1119:26)
    at /home/rafsawicki/dev/mqtt_test/node_modules/u8-mqtt/cjs/index.cjs:1491:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

After looking through the code, it seems that [this part of the mqtt reader](https://github.com/shanewholloway/js-u8-mqtt-packet/blob/master/code/decode/_utils.js#L79C22-L79C22) doesn't make any assertions and always expects the `mqtt_props.get` to return something. With large messages however, at some point an undefined is returned, and fails in the subsequent line when accessing the result. The error propagates to the catch block of the [async iterable processing](https://github.com/shanewholloway/js-u8-mqtt/blob/master/code/core.jsy#L100), which in turn results in the connection being dropped, even though there's a problem with a single message.

For convenience, I'm attaching an example JSON that I've used to re-create the error. It seems however that any large payload can trigger it.

[test.json](https://github.com/shanewholloway/js-u8-mqtt/files/13941498/test.json)

**Comment by shanewholloway** [comment]
Thanks for the nice actionable bug report. I've fixed the `u8-mqtt-packet` library so that errors decoding properties on MQTTv5 packets are recoverable now. May not fix your underlying issue, however.

My hypothesis is that the other side is using a new MQTT Property enum value that is not defined in the spec. The newly published versions (`u8-mqtt=0.6.0`, `u8-mqtt-packet=0.3.4`) create an `prop.error` value when encountering an unknown property.

If you find docs related to the MQTT property, please reference them here.

**Comment by rafsawicki** [comment]
I've tested the updated version today. I confirm that the newer version no longer gets disconnected. I don't see any errors or warnings in the console about the MQTT properties, so it appears that message is simply silently lost. I'm not sure how to access the `prop.error` value - if you can point me into how to check it, I can provide more information.

To try to rule out that the broker is doing something strange and out of spec, I've also tested on the different MQTT broker. My earlier tests were done using EMQX. I've now tested the large payload on the VerneMQ, but the behavior seems to be the same.

**Comment by rafsawicki** [comment]
For completeness sake, [I've prepared a repository with a reproduction scenario](https://github.com/rafsawicki/u8-mqtt-large-payload-issue) using aedes as a MQTT broker. Hopefully it will be useful in debugging the problem.

**Comment by shanewholloway** [comment]
Published `u8-mqtt=0.6.2`, `u8-mqtt-packet=0.3.5` with `console.warn` calls for unknown MQTT properties.

**Comment by rafsawicki** [comment]
I've re-ran my reproduction scenario with the latest version. No new warnings have been printed in the console and the message is still not received.

```
MQTT server listening on port 1883
[[u8-mqtt conn: on_live]] undefined undefined
[[u8-mqtt conn: on_conn]] undefined undefined
[[u8-mqtt conn: on_auth]] true undefined
[[u8-mqtt conn: on_ready]] undefined undefined

Publishing small payload
[mqtt.js] Got message with length 13
[u8-mqtt] Got message with length 13

Publishing large payload
[mqtt.js] Got message with length 11888891
```

**Comment by rafsawicki** [comment]
I now noticed that the new warnings were added only to the MQTT v5 client, while my reproduction scenario was based on MQTT 3.1.1, since that's the only version that aedes supports. I incorrectly assumed that the new warning was added to both versions.

I've re-tested using both MQTT versions, and also verified the exact maximum working message size, which is 2097146 bytes for MQTT 3.1.1 and 2097145 bytes when using MQTT 5 (so around 2 MB). In addition to that, there's a following warning printed when I'm sending my new test message, which is `x` character repeated over and over again.
```
Publishing large payload
[u8-mqtt-packet] unknown property: 120
[mqtt.js] Got message with length 2097146
```
120 value seems to be the ASCII value of the character that I'm now using, since if I replace the message with repeated `a` character, I get the following warning:
```
Publishing large payload
[u8-mqtt-packet] unknown property: 97
[mqtt.js] Got message with length 2097146
```

So it kinda seems that the library is trying to interpret a part of the message as a MQTT control byte?

**Comment by rafsawicki** [comment]
I went deeper through the code to analyze what is going on. If I'm not mistaken, it seems that the library simply miscalculates the message size when decoding large messages, which in turn messes up the rest of the message processing.

The main culprit seems to be the [decode_variant](https://github.com/shanewholloway/js-u8-mqtt-packet/blob/51d7b97ba05497ca0ba12e2868f9fcbe9c654612/code/mqtt_varint.js#L23) function, which, unlike `encode_varint` function, is hand written using if statements instead of a loop. This function is then used by the [raw_dispatch](https://github.com/shanewholloway/js-u8-mqtt-packet/blob/51d7b97ba05497ca0ba12e2868f9fcbe9c654612/code/framing.js#L4) function to calculate the message length, and then a packet is decoded based on that. When the message over 2 MB is sent, it seems that the number of max 4 chains mentioned in the comment is not sufficient to read the length correctly. The packet in [L24](https://github.com/shanewholloway/js-u8-mqtt-packet/blob/51d7b97ba05497ca0ba12e2868f9fcbe9c654612/code/framing.js#L24) of `mqtt_raw_dispach` is parsed incorrectly (e.g. a part of the message payload is interpreted as a topic), which results in warnings that you've added, as we're reading wrong parts of the buffer further down the road.

When I manually added additional if statement in the chain, the longer message was parsed correctly. I'm not sure however, if this should be the final solution, or if it should be re-worked somehow to correctly parse any message size (edit: up to 256MB I guess, since that's the maximum theoretical size limit).

**Comment by shanewholloway** [comment]
Thanks for the update! I had come to the same conclusion early this morning of a problem in `decode_varint` for large values and validated the fix using your wonderfully helpful reproduction repo. See [bugfix line for missing `i++`](https://github.com/shanewholloway/js-u8-mqtt-packet/commit/cf5639196113aff5266deb4024b9538feea7d604#r137397908) and added unit tests for varint round-tripping.

According to [the MQTT spec, the max varint](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011)  value is `268_435_455 (0x0fff_ffff)` -- which always fits in 4 bytes.


The fix also lead to an a review of the framing code in `raw_dispatch` you found. I identified a potential issue if the encoded packet length was fragmented and fixed that as well.

Please give versions `u8-mqtt=0.6.3`, `u8-mqtt-packet=0.4.1` a try -- and thank you for your awesome support tracking this down!

**Comment by rafsawicki** [comment]
I confirm that the newest version works correctly using both MQTT 3.1.1 and MQTT 5.

> Please give versions u8-mqtt=0.6.3, u8-mqtt-packet=0.4.1 a try -- and thank you for your awesome support tracking this down!

You're very much welcome, I'm glad that my reproduction repository have helped. That's the least I can do :) - this library has helped me a lot with not having to re-write one of my services in a completely different language, since MQTT.js doesn't properly support QoS1 and sending ACK after a message is processed (such setup blocks concurrent processing, which kills performance), and paho-mqtt is so old it doesn't support MQTT 5.
